#ifndef MEGAMANIAC_GAME_OBJECT_TYPES_H_
#define MEGAMANIAC_GAME_OBJECT_TYPES_H_

#define GO_TYPE_LINE		1
#define GO_TYPE_CREDITS		2
#define	GO_TYPE_SCORE		3
#define GO_TYPE_LIVES		4
#define GO_TYPE_QUIT		5
#define GO_TYPE_RESTART		6
#define GO_TYPE_SCORE_CHEATER	7
#define GO_TYPE_PLAYER		8
#define GO_TYPE_ENEMY1		9
#define GO_TYPE_ENEMY2		10
#define GO_TYPE_ENEMY3		11
#define GO_TYPE_ENEMY4		12
#define GO_TYPE_ENEMY5		13
#define GO_TYPE_ENEMY_MOVER	14
#define GO_TYPE_LEVEL_NAME	15
#define GO_TYPE_BULLET		16
#define GO_TYPE_BOMB_DROPPER	17
#define GO_TYPE_BOMB		18
#define GO_TYPE_LOST_SCREEN	19
#define GO_TYPE_LEVEL_CHANGER	20
#define GO_TYPE_PAUSER		21
#define GO_TYPE_PAUSE_SCREEN	22
#define GO_TYPE_TRACE_DRAWER	23
#define GO_TYPE_TRACE		24

#endif
