all: ZombieDash

LIBS=-lzdk01 -lncurses -lm -lrt
DIRS=-I../ZDK01 -L../ZDK01
FLAGS=-std=gnu99 -D_XOPEN_SOURCE=500 -Wall -Werror

clean:
	rm ZombieDash

rebuild: clean all

SRC=main.c game.c player.c zombie.c
HDR=game.h player.h zombie.h

ZombieDash: $(SRC) $(HDR) ../ZDK01/libzdk01.a
	gcc $(FLAGS) $(SRC) -o $@ $(DIRS) $(LIBS) 
